# Generated by Django 5.2.14 on 2026-06-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='filename',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
