# Generated by Django 5.2.14 on 2026-06-18 00:08

import dershop.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimage_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='filename',
            field=models.ImageField(blank=True, null=True, upload_to=dershop.common.models.get_unique_product_file_path),
        ),
    ]
